### ISSUE TITLE
Compilation error: Illegal type conversion: "TObject" to "LongInt"

### ISSUE THREAD

**Issue by rchastain** [wp-xyz/sunrise#1]
I am trying to compile the project under Linux with Lazarus 2.0.10 (FPC 3.2.0) and get this error:
```
sunmainform.pas(302,15) Error: Illegal type conversion: "TObject" to "LongInt"
```
```
    deltaT := integer(cbDeltaUTC.Items.Objects[cbDeltaUTC.ItemIndex]) / 240;
```

**Comment by rchastain** [comment]
Same error with Lazarus 2.3.0.

**Comment by wp-xyz** [comment]
Missed one of these typical 32-bit issues at 64-bit again (I normally work with the 32-bit IDE).
Fixed.

**Comment by rchastain** [comment]
Thanks.
